name: acdc
channels:
  - simpleitk
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - absl-py=0.7.0=py36_0
  - astor=0.7.1=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.1=openblas
  - bz2file=0.98=py_0
  - bzip2=1.0.6=h14c3975_1002
  - c-ares=1.15.0=h7b6447c_1
  - ca-certificates=2018.11.29=ha4d7672_0
  - cairo=1.14.12=h8948797_3
  - certifi=2018.11.29=py36_1000
  - cloudpickle=0.7.0=py_0
  - cudatoolkit=9.2=0
  - cudnn=7.3.1=cuda9.2_0
  - cupti=9.2.148=0
  - cycler=0.10.0=py36_0
  - cytoolz=0.9.0.1=py36h14c3975_1
  - dask-core=1.1.1=py_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.3.2=py36_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.1=h6dce934_1001
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.2=py36_0
  - giflib=5.1.4=h14c3975_1001
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.6.5=hd3a4fd2_1001
  - graphite2=1.3.13=hf484d3e_1000
  - grpcio=1.16.1=py36hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=py36h7918eee_0
  - harfbuzz=1.9.0=he243708_1001
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h9c2bf20_1
  - imageio=2.4.1=py36_0
  - intel-openmp=2019.1=144
  - ipython=7.2.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - jasper=1.900.1=h07fcdf6_1006
  - jedi=0.13.2=py36_0
  - jpeg=9c=h14c3975_1001
  - keras-applications=1.0.6=py36_0
  - keras-preprocessing=1.0.5=py36_0
  - kiwisolver=1.0.1=py36hf484d3e_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h14c3975_1004
  - libopenblas=0.3.3=h5a2b251_3
  - libpng=1.6.36=hbc83047_0
  - libprotobuf=3.6.1=hd408876_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libwebp=1.0.2=h576950b_1
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - markdown=3.0.1=py36_0
  - matplotlib=3.0.2=py36h8a2030e_1001
  - matplotlib-base=3.0.2=py36h167e16e_1001
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py36_0
  - mkl_random=1.0.2=py36_0
  - ncurses=6.1=he6710b0_1
  - nettle=3.4.1=h14c3975_1002
  - networkx=2.2=py36_1
  - nibabel=2.3.3=py_0
  - numpy=1.16.1=py36_blas_openblash1522bff_0
  - numpy-base=1.15.4=py36h2f8d375_0
  - olefile=0.46=py36_0
  - openblas=0.3.3=h9ac9557_1001
  - opencv=3.4.4=py36_blas_openblash85ad109_1203
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1a=h14c3975_1000
  - pandas=0.24.1=py36he6710b0_0
  - parso=0.3.2=py36_0
  - patsy=0.5.1=py36_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=5.4.1=py36h34e0f95_0
  - pip=19.0.1=py36_0
  - pixman=0.34.0=h14c3975_1003
  - prompt_toolkit=2.0.8=py_0
  - protobuf=3.6.1=py36he6710b0_0
  - ptyprocess=0.6.0=py36_0
  - pydicom=1.2.2=py_0
  - pygments=2.3.1=py36_0
  - pyparsing=2.3.1=py36_0
  - pyqt=5.6.0=py36_2
  - python=3.6.8=h0371630_0
  - python-dateutil=2.7.5=py36_0
  - pytz=2018.9=py36_0
  - pywavelets=1.0.1=py36hdd07704_0
  - qt=5.6.3=h8bf5577_3
  - readline=7.0=h7b6447c_5
  - scikit-image=0.14.1=py36he6710b0_0
  - scipy=1.2.1=py36_blas_openblash1522bff_0
  - seaborn=0.9.0=py36_0
  - setuptools=40.8.0=py36_0
  - simpleitk=1.2.0=py36hf484d3e_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py36_0
  - sqlite=3.26.0=h7b6447c_0
  - statsmodels=0.9.0=py36h035aef0_0
  - tensorboard=1.12.2=py36he6710b0_0
  - tensorflow=1.12.0=gpu_py36he74679b_0
  - tensorflow-base=1.12.0=gpu_py36had579c0_0
  - tensorflow-gpu=1.12.0=h0d30ee6_0
  - termcolor=1.1.0=py36_1
  - tk=8.6.8=hbc83047_0
  - toolz=0.9.0=py36_0
  - tornado=5.1.1=py36h7b6447c_0
  - traitlets=4.3.2=py36h674d592_0
  - wcwidth=0.1.7=py36_0
  - werkzeug=0.14.1=py36_0
  - wheel=0.32.3=py36_0
  - x264=1!152.20180717=h14c3975_1001
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - medpy==0.4.0
prefix: /home/diego/anaconda3/envs/acdc

